// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	BallWeightOptionDefault = 0
	BallWeightOptionLight = 1
	BallWeightOptionHeavy = 2
	BallWeightOptionSuper_Light = 3
)

var EnumNamesBallWeightOption = map[int]string{
	BallWeightOptionDefault:"Default",
	BallWeightOptionLight:"Light",
	BallWeightOptionHeavy:"Heavy",
	BallWeightOptionSuper_Light:"Super_Light",
}

