// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	BallTypeOptionDefault = 0
	BallTypeOptionCube = 1
	BallTypeOptionPuck = 2
	BallTypeOptionBasketball = 3
)

var EnumNamesBallTypeOption = map[int]string{
	BallTypeOptionDefault:"Default",
	BallTypeOptionCube:"Cube",
	BallTypeOptionPuck:"Puck",
	BallTypeOptionBasketball:"Basketball",
}

