// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	BallSizeOptionDefault = 0
	BallSizeOptionSmall = 1
	BallSizeOptionLarge = 2
	BallSizeOptionGigantic = 3
)

var EnumNamesBallSizeOption = map[int]string{
	BallSizeOptionDefault:"Default",
	BallSizeOptionSmall:"Small",
	BallSizeOptionLarge:"Large",
	BallSizeOptionGigantic:"Gigantic",
}

