// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Bool struct {
	_tab flatbuffers.Struct
}

func (rcv *Bool) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Bool) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Bool) Val() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Bool) MutateVal(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateBool(builder *flatbuffers.Builder, val byte) flatbuffers.UOffsetT {
	builder.Prep(1, 1)
	builder.PrependByte(val)
	return builder.Offset()
}
