// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	BoostStrengthOptionOne = 0
	BoostStrengthOptionOneAndAHalf = 1
	BoostStrengthOptionTwo = 2
	BoostStrengthOptionTen = 3
)

var EnumNamesBoostStrengthOption = map[int]string{
	BoostStrengthOptionOne:"One",
	BoostStrengthOptionOneAndAHalf:"OneAndAHalf",
	BoostStrengthOptionTwo:"Two",
	BoostStrengthOptionTen:"Ten",
}

