// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// A console command which we will try to execute inside Rocket League.
/// See https://github.com/RLBot/RLBot/wiki/Console-Commands for a list of known commands.
type ConsoleCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsConsoleCommand(buf []byte, offset flatbuffers.UOffsetT) *ConsoleCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsoleCommand{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ConsoleCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsoleCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsoleCommand) Command() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConsoleCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ConsoleCommandAddCommand(builder *flatbuffers.Builder, command flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(command), 0)
}
func ConsoleCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
