// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	DemolishOptionDefault = 0
	DemolishOptionDisabled = 1
	DemolishOptionFriendly_Fire = 2
	DemolishOptionOn_Contact = 3
	DemolishOptionOn_Contact_FF = 4
)

var EnumNamesDemolishOption = map[int]string{
	DemolishOptionDefault:"Default",
	DemolishOptionDisabled:"Disabled",
	DemolishOptionFriendly_Fire:"Friendly_Fire",
	DemolishOptionOn_Contact:"On_Contact",
	DemolishOptionOn_Contact_FF:"On_Contact_FF",
}

