// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DesiredBallState struct {
	_tab flatbuffers.Table
}

func GetRootAsDesiredBallState(buf []byte, offset flatbuffers.UOffsetT) *DesiredBallState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DesiredBallState{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DesiredBallState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DesiredBallState) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DesiredBallState) Physics(obj *DesiredPhysics) *DesiredPhysics {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DesiredPhysics)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DesiredBallStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DesiredBallStateAddPhysics(builder *flatbuffers.Builder, physics flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(physics), 0)
}
func DesiredBallStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
