// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DropshotTile struct {
	_tab flatbuffers.Table
}

func GetRootAsDropshotTile(buf []byte, offset flatbuffers.UOffsetT) *DropshotTile {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DropshotTile{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DropshotTile) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DropshotTile) Table() flatbuffers.Table {
	return rcv._tab
}

/// The amount of damage the tile has sustained.
func (rcv *DropshotTile) TileState() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

/// The amount of damage the tile has sustained.
func (rcv *DropshotTile) MutateTileState(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func DropshotTileStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DropshotTileAddTileState(builder *flatbuffers.Builder, tileState int8) {
	builder.PrependInt8Slot(0, tileState, 0)
}
func DropshotTileEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
