// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	/// Restart the match if any match settings differ. This is the default because old RLBot always worked this way.
	ExistingMatchBehaviorRestart_If_Different = 0
	/// Always restart the match, even if config is identical
	ExistingMatchBehaviorRestart = 1
	/// Never restart an existing match, just try to remove or spawn cars to match the configuration.
	/// If we are not in the middle of a match, a match will be started. Handy for LAN matches.
	ExistingMatchBehaviorContinue_And_Spawn = 2
)

var EnumNamesExistingMatchBehavior = map[int]string{
	ExistingMatchBehaviorRestart_If_Different:"Restart_If_Different",
	ExistingMatchBehaviorRestart:"Restart",
	ExistingMatchBehaviorContinue_And_Spawn:"Continue_And_Spawn",
}

