// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldInfo(buf []byte, offset flatbuffers.UOffsetT) *FieldInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldInfo{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FieldInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldInfo) BoostPads(obj *BoostPad, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FieldInfo) BoostPadsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FieldInfo) Goals(obj *GoalInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FieldInfo) GoalsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func FieldInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FieldInfoAddBoostPads(builder *flatbuffers.Builder, boostPads flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(boostPads), 0)
}
func FieldInfoStartBoostPadsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FieldInfoAddGoals(builder *flatbuffers.Builder, goals flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(goals), 0)
}
func FieldInfoStartGoalsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FieldInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
