// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Float struct {
	_tab flatbuffers.Struct
}

func (rcv *Float) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Float) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Float) Val() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Float) MutateVal(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateFloat(builder *flatbuffers.Builder, val float32) flatbuffers.UOffsetT {
	builder.Prep(4, 4)
	builder.PrependFloat32(val)
	return builder.Offset()
}
