// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	GameSpeedOptionDefault = 0
	GameSpeedOptionSlo_Mo = 1
	GameSpeedOptionTime_Warp = 2
)

var EnumNamesGameSpeedOption = map[int]string{
	GameSpeedOptionDefault:"Default",
	GameSpeedOptionSlo_Mo:"Slo_Mo",
	GameSpeedOptionTime_Warp:"Time_Warp",
}

