// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	GameModeSoccer = 0
	GameModeHoops = 1
	GameModeDropshot = 2
	GameModeHockey = 3
	GameModeRumble = 4
	GameModeHeatseeker = 5
	GameModeGridiron = 6
)

var EnumNamesGameMode = map[int]string{
	GameModeSoccer:"Soccer",
	GameModeHoops:"Hoops",
	GameModeDropshot:"Dropshot",
	GameModeHockey:"Hockey",
	GameModeRumble:"Rumble",
	GameModeHeatseeker:"Heatseeker",
	GameModeGridiron:"Gridiron",
}

