// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	GameMapDFHStadium = 0
	GameMapMannfield = 1
	GameMapChampionsField = 2
	GameMapUrbanCentral = 3
	GameMapBeckwithPark = 4
	GameMapUtopiaColiseum = 5
	GameMapWasteland = 6
	GameMapNeoTokyo = 7
	GameMapAquaDome = 8
	GameMapStarbaseArc = 9
	GameMapFarmstead = 10
	GameMapSaltyShores = 11
	GameMapDFHStadium_Stormy = 12
	GameMapDFHStadium_Day = 13
	GameMapMannfield_Stormy = 14
	GameMapMannfield_Night = 15
	GameMapChampionsField_Day = 16
	GameMapBeckwithPark_Stormy = 17
	GameMapBeckwithPark_Midnight = 18
	GameMapUrbanCentral_Night = 19
	GameMapUrbanCentral_Dawn = 20
	GameMapUtopiaColiseum_Dusk = 21
	GameMapDFHStadium_Snowy = 22
	GameMapMannfield_Snowy = 23
	GameMapUtopiaColiseum_Snowy = 24
	GameMapBadlands = 25
	GameMapBadlands_Night = 26
	GameMapTokyoUnderpass = 27
	GameMapArctagon = 28
	GameMapPillars = 29
	GameMapCosmic = 30
	GameMapDoubleGoal = 31
	GameMapOctagon = 32
	GameMapUnderpass = 33
	GameMapUtopiaRetro = 34
	GameMapHoops_DunkHouse = 35
	GameMapDropShot_Core707 = 36
	GameMapThrowbackStadium = 37
	GameMapForbiddenTemple = 38
	GameMapRivalsArena = 39
	GameMapFarmstead_Night = 40
	GameMapSaltyShores_Night = 41
	GameMapNeonFields = 42
	GameMapDFHStadium_Circuit = 43
)

var EnumNamesGameMap = map[int]string{
	GameMapDFHStadium:"DFHStadium",
	GameMapMannfield:"Mannfield",
	GameMapChampionsField:"ChampionsField",
	GameMapUrbanCentral:"UrbanCentral",
	GameMapBeckwithPark:"BeckwithPark",
	GameMapUtopiaColiseum:"UtopiaColiseum",
	GameMapWasteland:"Wasteland",
	GameMapNeoTokyo:"NeoTokyo",
	GameMapAquaDome:"AquaDome",
	GameMapStarbaseArc:"StarbaseArc",
	GameMapFarmstead:"Farmstead",
	GameMapSaltyShores:"SaltyShores",
	GameMapDFHStadium_Stormy:"DFHStadium_Stormy",
	GameMapDFHStadium_Day:"DFHStadium_Day",
	GameMapMannfield_Stormy:"Mannfield_Stormy",
	GameMapMannfield_Night:"Mannfield_Night",
	GameMapChampionsField_Day:"ChampionsField_Day",
	GameMapBeckwithPark_Stormy:"BeckwithPark_Stormy",
	GameMapBeckwithPark_Midnight:"BeckwithPark_Midnight",
	GameMapUrbanCentral_Night:"UrbanCentral_Night",
	GameMapUrbanCentral_Dawn:"UrbanCentral_Dawn",
	GameMapUtopiaColiseum_Dusk:"UtopiaColiseum_Dusk",
	GameMapDFHStadium_Snowy:"DFHStadium_Snowy",
	GameMapMannfield_Snowy:"Mannfield_Snowy",
	GameMapUtopiaColiseum_Snowy:"UtopiaColiseum_Snowy",
	GameMapBadlands:"Badlands",
	GameMapBadlands_Night:"Badlands_Night",
	GameMapTokyoUnderpass:"TokyoUnderpass",
	GameMapArctagon:"Arctagon",
	GameMapPillars:"Pillars",
	GameMapCosmic:"Cosmic",
	GameMapDoubleGoal:"DoubleGoal",
	GameMapOctagon:"Octagon",
	GameMapUnderpass:"Underpass",
	GameMapUtopiaRetro:"UtopiaRetro",
	GameMapHoops_DunkHouse:"Hoops_DunkHouse",
	GameMapDropShot_Core707:"DropShot_Core707",
	GameMapThrowbackStadium:"ThrowbackStadium",
	GameMapForbiddenTemple:"ForbiddenTemple",
	GameMapRivalsArena:"RivalsArena",
	GameMapFarmstead_Night:"Farmstead_Night",
	GameMapSaltyShores_Night:"SaltyShores_Night",
	GameMapNeonFields:"NeonFields",
	GameMapDFHStadium_Circuit:"DFHStadium_Circuit",
}

