// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GameMessageWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsGameMessageWrapper(buf []byte, offset flatbuffers.UOffsetT) *GameMessageWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GameMessageWrapper{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GameMessageWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GameMessageWrapper) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GameMessageWrapper) MessageType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameMessageWrapper) MutateMessageType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *GameMessageWrapper) Message(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func GameMessageWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GameMessageWrapperAddMessageType(builder *flatbuffers.Builder, MessageType byte) {
	builder.PrependByteSlot(0, MessageType, 0)
}
func GameMessageWrapperAddMessage(builder *flatbuffers.Builder, Message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Message), 0)
}
func GameMessageWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
