// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	GameMessageNONE = 0
	GameMessagePlayerStatEvent = 1
	GameMessagePlayerSpectate = 2
	GameMessagePlayerInputChange = 3
)

var EnumNamesGameMessage = map[int]string{
	GameMessageNONE:"NONE",
	GameMessagePlayerStatEvent:"PlayerStatEvent",
	GameMessagePlayerSpectate:"PlayerSpectate",
	GameMessagePlayerInputChange:"PlayerInputChange",
}

