// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	GravityOptionDefault = 0
	GravityOptionLow = 1
	GravityOptionHigh = 2
	GravityOptionSuper_High = 3
)

var EnumNamesGravityOption = map[int]string{
	GravityOptionDefault:"Default",
	GravityOptionLow:"Low",
	GravityOptionHigh:"High",
	GravityOptionSuper_High:"Super_High",
}

