// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	MatchLengthFive_Minutes = 0
	MatchLengthTen_Minutes = 1
	MatchLengthTwenty_Minutes = 2
	MatchLengthUnlimited = 3
)

var EnumNamesMatchLength = map[int]string{
	MatchLengthFive_Minutes:"Five_Minutes",
	MatchLengthTen_Minutes:"Ten_Minutes",
	MatchLengthTwenty_Minutes:"Twenty_Minutes",
	MatchLengthUnlimited:"Unlimited",
}

