// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	MaxScoreUnlimited = 0
	MaxScoreOne_Goal = 1
	MaxScoreThree_Goals = 2
	MaxScoreFive_Goals = 3
)

var EnumNamesMaxScore = map[int]string{
	MaxScoreUnlimited:"Unlimited",
	MaxScoreOne_Goal:"One_Goal",
	MaxScoreThree_Goals:"Three_Goals",
	MaxScoreFive_Goals:"Five_Goals",
}

