// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	PlayerClassNONE = 0
	PlayerClassRLBotPlayer = 1
	PlayerClassHumanPlayer = 2
	PlayerClassPsyonixBotPlayer = 3
	PlayerClassPartyMemberBotPlayer = 4
)

var EnumNamesPlayerClass = map[int]string{
	PlayerClassNONE:"NONE",
	PlayerClassRLBotPlayer:"RLBotPlayer",
	PlayerClassHumanPlayer:"HumanPlayer",
	PlayerClassPsyonixBotPlayer:"PsyonixBotPlayer",
	PlayerClassPartyMemberBotPlayer:"PartyMemberBotPlayer",
}

