// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Rigid body state for a player / car in the game. Includes the latest
/// controller input, which is otherwise difficult to correlate with consequences.
type PlayerRigidBodyState struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerRigidBodyState(buf []byte, offset flatbuffers.UOffsetT) *PlayerRigidBodyState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerRigidBodyState{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PlayerRigidBodyState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerRigidBodyState) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerRigidBodyState) State(obj *RigidBodyState) *RigidBodyState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(RigidBodyState)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PlayerRigidBodyState) Input(obj *ControllerState) *ControllerState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ControllerState)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PlayerRigidBodyStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PlayerRigidBodyStateAddState(builder *flatbuffers.Builder, state flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(state), 0)
}
func PlayerRigidBodyStateAddInput(builder *flatbuffers.Builder, input flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(input), 0)
}
func PlayerRigidBodyStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
