// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// A psyonix bot, e.g. All Star bot
type PsyonixBotPlayer struct {
	_tab flatbuffers.Table
}

func GetRootAsPsyonixBotPlayer(buf []byte, offset flatbuffers.UOffsetT) *PsyonixBotPlayer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PsyonixBotPlayer{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PsyonixBotPlayer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PsyonixBotPlayer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PsyonixBotPlayer) BotSkill() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PsyonixBotPlayer) MutateBotSkill(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func PsyonixBotPlayerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PsyonixBotPlayerAddBotSkill(builder *flatbuffers.Builder, botSkill float32) {
	builder.PrependFloat32Slot(0, botSkill, 0.0)
}
func PsyonixBotPlayerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
