// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	QuickChatSelectionInformation_IGotIt = 0
	QuickChatSelectionInformation_NeedBoost = 1
	QuickChatSelectionInformation_TakeTheShot = 2
	QuickChatSelectionInformation_Defending = 3
	QuickChatSelectionInformation_GoForIt = 4
	QuickChatSelectionInformation_Centering = 5
	QuickChatSelectionInformation_AllYours = 6
	QuickChatSelectionInformation_InPosition = 7
	QuickChatSelectionInformation_Incoming = 8
	QuickChatSelectionCompliments_NiceShot = 9
	QuickChatSelectionCompliments_GreatPass = 10
	QuickChatSelectionCompliments_Thanks = 11
	QuickChatSelectionCompliments_WhatASave = 12
	QuickChatSelectionCompliments_NiceOne = 13
	QuickChatSelectionCompliments_WhatAPlay = 14
	QuickChatSelectionCompliments_GreatClear = 15
	QuickChatSelectionCompliments_NiceBlock = 16
	QuickChatSelectionReactions_OMG = 17
	QuickChatSelectionReactions_Noooo = 18
	QuickChatSelectionReactions_Wow = 19
	QuickChatSelectionReactions_CloseOne = 20
	QuickChatSelectionReactions_NoWay = 21
	QuickChatSelectionReactions_HolyCow = 22
	QuickChatSelectionReactions_Whew = 23
	QuickChatSelectionReactions_Siiiick = 24
	QuickChatSelectionReactions_Calculated = 25
	QuickChatSelectionReactions_Savage = 26
	QuickChatSelectionReactions_Okay = 27
	QuickChatSelectionApologies_Cursing = 28
	QuickChatSelectionApologies_NoProblem = 29
	QuickChatSelectionApologies_Whoops = 30
	QuickChatSelectionApologies_Sorry = 31
	QuickChatSelectionApologies_MyBad = 32
	QuickChatSelectionApologies_Oops = 33
	QuickChatSelectionApologies_MyFault = 34
	QuickChatSelectionPostGame_Gg = 35
	QuickChatSelectionPostGame_WellPlayed = 36
	QuickChatSelectionPostGame_ThatWasFun = 37
	QuickChatSelectionPostGame_Rematch = 38
	QuickChatSelectionPostGame_OneMoreGame = 39
	QuickChatSelectionPostGame_WhatAGame = 40
	QuickChatSelectionPostGame_NiceMoves = 41
	QuickChatSelectionPostGame_EverybodyDance = 42
	/// Custom text chats made by bot makers
	QuickChatSelectionMaxPysonixQuickChatPresets = 43
	/// Waste of CPU cycles
	QuickChatSelectionCustom_Toxic_WasteCPU = 44
	/// Git gud*
	QuickChatSelectionCustom_Toxic_GitGut = 45
	/// De-Allocate Yourself
	QuickChatSelectionCustom_Toxic_DeAlloc = 46
	/// 404: Your skill not found
	QuickChatSelectionCustom_Toxic_404NoSkill = 47
	/// Get a virus
	QuickChatSelectionCustom_Toxic_CatchVirus = 48
	/// Passing!
	QuickChatSelectionCustom_Useful_Passing = 49
	/// Faking!
	QuickChatSelectionCustom_Useful_Faking = 50
	/// Demoing!
	QuickChatSelectionCustom_Useful_Demoing = 51
	/// BOOPING
	QuickChatSelectionCustom_Useful_Bumping = 52
	/// The chances of that was 47525 to 1*
	QuickChatSelectionCustom_Compliments_TinyChances = 53
	/// Who upped your skill level?
	QuickChatSelectionCustom_Compliments_SkillLevel = 54
	/// Your programmer should be proud
	QuickChatSelectionCustom_Compliments_proud = 55
	/// You're the GC of Bots
	QuickChatSelectionCustom_Compliments_GC = 56
	/// Are you <Insert Pro>Bot? *
	QuickChatSelectionCustom_Compliments_Pro = 57
	/// Lag
	QuickChatSelectionCustom_Excuses_Lag = 58
	/// Ghost inputs
	QuickChatSelectionCustom_Excuses_GhostInputs = 59
	/// RIGGED
	QuickChatSelectionCustom_Excuses_Rigged = 60
	/// Mafia plays!
	QuickChatSelectionCustom_Toxic_MafiaPlays = 61
	/// Yeet!
	QuickChatSelectionCustom_Exclamation_Yeet = 62
)

var EnumNamesQuickChatSelection = map[int]string{
	QuickChatSelectionInformation_IGotIt:"Information_IGotIt",
	QuickChatSelectionInformation_NeedBoost:"Information_NeedBoost",
	QuickChatSelectionInformation_TakeTheShot:"Information_TakeTheShot",
	QuickChatSelectionInformation_Defending:"Information_Defending",
	QuickChatSelectionInformation_GoForIt:"Information_GoForIt",
	QuickChatSelectionInformation_Centering:"Information_Centering",
	QuickChatSelectionInformation_AllYours:"Information_AllYours",
	QuickChatSelectionInformation_InPosition:"Information_InPosition",
	QuickChatSelectionInformation_Incoming:"Information_Incoming",
	QuickChatSelectionCompliments_NiceShot:"Compliments_NiceShot",
	QuickChatSelectionCompliments_GreatPass:"Compliments_GreatPass",
	QuickChatSelectionCompliments_Thanks:"Compliments_Thanks",
	QuickChatSelectionCompliments_WhatASave:"Compliments_WhatASave",
	QuickChatSelectionCompliments_NiceOne:"Compliments_NiceOne",
	QuickChatSelectionCompliments_WhatAPlay:"Compliments_WhatAPlay",
	QuickChatSelectionCompliments_GreatClear:"Compliments_GreatClear",
	QuickChatSelectionCompliments_NiceBlock:"Compliments_NiceBlock",
	QuickChatSelectionReactions_OMG:"Reactions_OMG",
	QuickChatSelectionReactions_Noooo:"Reactions_Noooo",
	QuickChatSelectionReactions_Wow:"Reactions_Wow",
	QuickChatSelectionReactions_CloseOne:"Reactions_CloseOne",
	QuickChatSelectionReactions_NoWay:"Reactions_NoWay",
	QuickChatSelectionReactions_HolyCow:"Reactions_HolyCow",
	QuickChatSelectionReactions_Whew:"Reactions_Whew",
	QuickChatSelectionReactions_Siiiick:"Reactions_Siiiick",
	QuickChatSelectionReactions_Calculated:"Reactions_Calculated",
	QuickChatSelectionReactions_Savage:"Reactions_Savage",
	QuickChatSelectionReactions_Okay:"Reactions_Okay",
	QuickChatSelectionApologies_Cursing:"Apologies_Cursing",
	QuickChatSelectionApologies_NoProblem:"Apologies_NoProblem",
	QuickChatSelectionApologies_Whoops:"Apologies_Whoops",
	QuickChatSelectionApologies_Sorry:"Apologies_Sorry",
	QuickChatSelectionApologies_MyBad:"Apologies_MyBad",
	QuickChatSelectionApologies_Oops:"Apologies_Oops",
	QuickChatSelectionApologies_MyFault:"Apologies_MyFault",
	QuickChatSelectionPostGame_Gg:"PostGame_Gg",
	QuickChatSelectionPostGame_WellPlayed:"PostGame_WellPlayed",
	QuickChatSelectionPostGame_ThatWasFun:"PostGame_ThatWasFun",
	QuickChatSelectionPostGame_Rematch:"PostGame_Rematch",
	QuickChatSelectionPostGame_OneMoreGame:"PostGame_OneMoreGame",
	QuickChatSelectionPostGame_WhatAGame:"PostGame_WhatAGame",
	QuickChatSelectionPostGame_NiceMoves:"PostGame_NiceMoves",
	QuickChatSelectionPostGame_EverybodyDance:"PostGame_EverybodyDance",
	QuickChatSelectionMaxPysonixQuickChatPresets:"MaxPysonixQuickChatPresets",
	QuickChatSelectionCustom_Toxic_WasteCPU:"Custom_Toxic_WasteCPU",
	QuickChatSelectionCustom_Toxic_GitGut:"Custom_Toxic_GitGut",
	QuickChatSelectionCustom_Toxic_DeAlloc:"Custom_Toxic_DeAlloc",
	QuickChatSelectionCustom_Toxic_404NoSkill:"Custom_Toxic_404NoSkill",
	QuickChatSelectionCustom_Toxic_CatchVirus:"Custom_Toxic_CatchVirus",
	QuickChatSelectionCustom_Useful_Passing:"Custom_Useful_Passing",
	QuickChatSelectionCustom_Useful_Faking:"Custom_Useful_Faking",
	QuickChatSelectionCustom_Useful_Demoing:"Custom_Useful_Demoing",
	QuickChatSelectionCustom_Useful_Bumping:"Custom_Useful_Bumping",
	QuickChatSelectionCustom_Compliments_TinyChances:"Custom_Compliments_TinyChances",
	QuickChatSelectionCustom_Compliments_SkillLevel:"Custom_Compliments_SkillLevel",
	QuickChatSelectionCustom_Compliments_proud:"Custom_Compliments_proud",
	QuickChatSelectionCustom_Compliments_GC:"Custom_Compliments_GC",
	QuickChatSelectionCustom_Compliments_Pro:"Custom_Compliments_Pro",
	QuickChatSelectionCustom_Excuses_Lag:"Custom_Excuses_Lag",
	QuickChatSelectionCustom_Excuses_GhostInputs:"Custom_Excuses_GhostInputs",
	QuickChatSelectionCustom_Excuses_Rigged:"Custom_Excuses_Rigged",
	QuickChatSelectionCustom_Toxic_MafiaPlays:"Custom_Toxic_MafiaPlays",
	QuickChatSelectionCustom_Exclamation_Yeet:"Custom_Exclamation_Yeet",
}

