// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type QuickChatMessages struct {
	_tab flatbuffers.Table
}

func GetRootAsQuickChatMessages(buf []byte, offset flatbuffers.UOffsetT) *QuickChatMessages {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &QuickChatMessages{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *QuickChatMessages) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *QuickChatMessages) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *QuickChatMessages) Messages(obj *QuickChat, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *QuickChatMessages) MessagesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func QuickChatMessagesStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func QuickChatMessagesAddMessages(builder *flatbuffers.Builder, messages flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(messages), 0)
}
func QuickChatMessagesStartMessagesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func QuickChatMessagesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
