// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	RenderTypeDrawLine2D = 1
	RenderTypeDrawLine3D = 2
	RenderTypeDrawLine2D_3D = 3
	RenderTypeDrawRect2D = 4
	RenderTypeDrawRect3D = 5
	RenderTypeDrawString2D = 6
	RenderTypeDrawString3D = 7
	RenderTypeDrawCenteredRect3D = 8
)

var EnumNamesRenderType = map[int]string{
	RenderTypeDrawLine2D:"DrawLine2D",
	RenderTypeDrawLine3D:"DrawLine3D",
	RenderTypeDrawLine2D_3D:"DrawLine2D_3D",
	RenderTypeDrawRect2D:"DrawRect2D",
	RenderTypeDrawRect3D:"DrawRect3D",
	RenderTypeDrawString2D:"DrawString2D",
	RenderTypeDrawString3D:"DrawString3D",
	RenderTypeDrawCenteredRect3D:"DrawCenteredRect3D",
}

