// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	RumbleOptionNo_Rumble = 0
	RumbleOptionDefault = 1
	RumbleOptionSlow = 2
	RumbleOptionCivilized = 3
	RumbleOptionDestruction_Derby = 4
	RumbleOptionSpring_Loaded = 5
	RumbleOptionSpikes_Only = 6
	RumbleOptionSpike_Rush = 7
)

var EnumNamesRumbleOption = map[int]string{
	RumbleOptionNo_Rumble:"No_Rumble",
	RumbleOptionDefault:"Default",
	RumbleOptionSlow:"Slow",
	RumbleOptionCivilized:"Civilized",
	RumbleOptionDestruction_Derby:"Destruction_Derby",
	RumbleOptionSpring_Loaded:"Spring_Loaded",
	RumbleOptionSpikes_Only:"Spikes_Only",
	RumbleOptionSpike_Rush:"Spike_Rush",
}

