// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SphereShape struct {
	_tab flatbuffers.Table
}

func GetRootAsSphereShape(buf []byte, offset flatbuffers.UOffsetT) *SphereShape {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SphereShape{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SphereShape) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SphereShape) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SphereShape) Diameter() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *SphereShape) MutateDiameter(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func SphereShapeStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SphereShapeAddDiameter(builder *flatbuffers.Builder, diameter float32) {
	builder.PrependFloat32Slot(0, diameter, 0.0)
}
func SphereShapeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
