// automatically generated by the FlatBuffers compiler, do not modify

package flat

const (
	TileStateUnknown = 0
	/// The default state of the tiles.
	TileStateFilled = 1
	/// The state when a tile has been damaged.
	TileStateDamaged = 2
	/// The state of a tile when it is open and a goal can be scored.
	TileStateOpen = 3
)

var EnumNamesTileState = map[int]string{
	TileStateUnknown:"Unknown",
	TileStateFilled:"Filled",
	TileStateDamaged:"Damaged",
	TileStateOpen:"Open",
}

