// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// A minimal version of the game tick packet, useful when bandwidth needs to be conserved.
type TinyPacket struct {
	_tab flatbuffers.Table
}

func GetRootAsTinyPacket(buf []byte, offset flatbuffers.UOffsetT) *TinyPacket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TinyPacket{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TinyPacket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TinyPacket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TinyPacket) Players(obj *TinyPlayer, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TinyPacket) PlayersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TinyPacket) Ball(obj *TinyBall) *TinyBall {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TinyBall)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TinyPacketStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TinyPacketAddPlayers(builder *flatbuffers.Builder, players flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(players), 0)
}
func TinyPacketStartPlayersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TinyPacketAddBall(builder *flatbuffers.Builder, ball flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(ball), 0)
}
func TinyPacketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
