// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// A minimal version of the ball, useful when bandwidth needs to be conserved.
type TinyBall struct {
	_tab flatbuffers.Table
}

func GetRootAsTinyBall(buf []byte, offset flatbuffers.UOffsetT) *TinyBall {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TinyBall{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TinyBall) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TinyBall) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TinyBall) Location(obj *Vector3) *Vector3 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector3)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TinyBall) Velocity(obj *Vector3) *Vector3 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector3)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TinyBallStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TinyBallAddLocation(builder *flatbuffers.Builder, location flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(location), 0)
}
func TinyBallAddVelocity(builder *flatbuffers.Builder, velocity flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(velocity), 0)
}
func TinyBallEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
